databases:
  - name: collegedashboard
    # databaseName: collegedashboard
    # user: collagedashboard_user
    ipAllowList: []

services:
  - type: web
    name: online-school
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collegedashboard
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
   - type: redis
     name: redis
     ipAllowList: []
     plan: free
     maxmemoryPolicy: noeviction
